<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PRAKASH-PC" ignored="0" name="Contact Happy path" tests="1" failures="1" timestamp="10 May 2021 01:46:56 GMT" time="26.029" errors="0">
  <testcase name="sendMessage" time="8.854" classname="com.everbridge.testcases.ContactTest">
    <failure type="java.lang.AssertionError" message="expected [Your message has been successfully sent to our team.] but found [Your message has been successfully sent to our te.]">
      <![CDATA[java.lang.AssertionError: expected [Your message has been successfully sent to our team.] but found [Your message has been successfully sent to our te.]
at com.everbridge.testcases.ContactTest.sendMessage(ContactTest.java:44)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sendMessage -->
</testsuite> <!-- Contact Happy path -->
